### ISSUE TITLE
Consider using plain RFC4648 Base64 encoding instead of URL-safe Base64

### ISSUE THREAD

**Issue by mp911de** [hashicorp/vault-plugin-auth-pcf#25]
Using URL-safe RFC4648 encoding comes a bit of a surprise when using PCF authentication as every other Vault API accepting Base64-encoded data uses the regular variant.

What is the reason for using URL-safe base64 encoding? Please switch to the regular variant as a specific Base64 variant is a reliable source for bugs for implementors. Currently, only code samples mention the use of URL-safe base64. Reference docs and API docs do not mention this requirement.

**Comment by tyrannosaurus-becks** [comment]
That's a valid request. We could add support for both, to ensure backwards compatibility in case anyone is already code-complete using the client.

**Comment by mp911de** [comment]
Thanks a lot for addressing our feedback.

**Comment by kalafut** [comment]
@mp911de FYI, we had some discussion after that PR was merged and ended up doing something slightly different. Instead of a new API parameter (which I had made mention of on the other GH issue), signatures have a prefix. They'll be formatted like: `v1:<my std-base64 signature>`.  We will still accept `<my url-base64 signature>` for decoding.

**Comment by mp911de** [comment]
That is an overall better approach because v1: draws attention to the documentation and helps with understanding.
